/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 * This class represents the GUI for add member menu in a sports league system.
 * It allows users to select which member to add to the system It also provides
 * options to navigate back to the add members option or exit the application.
 *
 * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
 */
public class AddMemberMenu extends javax.swing.JFrame {

    /**
     * Creates new form AddMemberMenu
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    public AddMemberMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        memberImg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnManager = new javax.swing.JButton();
        btnPlayer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(107, 112, 92));
        jPanel1.setMaximumSize(new java.awt.Dimension(1220, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1220, 630));

        btnBack.setBackground(new java.awt.Color(221, 190, 169));
        btnBack.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(221, 190, 169));
        btnExit.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 232, 214));
        jLabel2.setText("Add Member");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/smallLogo.png"))); // NOI18N

        memberImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/member.jpeg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/manager.jpg"))); // NOI18N

        btnManager.setBackground(new java.awt.Color(221, 190, 169));
        btnManager.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManager.setText("Manager");
        btnManager.setMaximumSize(new java.awt.Dimension(75, 31));
        btnManager.setMinimumSize(new java.awt.Dimension(75, 31));
        btnManager.setPreferredSize(new java.awt.Dimension(75, 31));
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });

        btnPlayer.setBackground(new java.awt.Color(221, 190, 169));
        btnPlayer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPlayer.setText("Player");
        btnPlayer.setMaximumSize(new java.awt.Dimension(75, 31));
        btnPlayer.setMinimumSize(new java.awt.Dimension(75, 31));
        btnPlayer.setPreferredSize(new java.awt.Dimension(75, 31));
        btnPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(278, 278, 278)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(151, 151, 151)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberImg))
                .addGap(305, 305, 305))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel2)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(memberImg))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManager, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1220, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Handles the event when the mouse enters the back button. Changes the
     * background color of the back button to a specific color.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnBackMouseEntered
    /**
     * Handles the event when the mouse exits the back button. Changes the
     * background color of the back button back to its default color.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnBackMouseExited
    /**
     * Handles the event when the back button is clicked. Opens the Members
     * Options window and closes the current window.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent triggering this method.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MembersOptions membersOptions = new MembersOptions();
        membersOptions.setVisible(true); //show teams options window
        dispose(); //hide the current window
    }//GEN-LAST:event_btnBackActionPerformed
    /**
     * Handles the event when the mouse enters the exit button. Changes the
     * background color of the exit button to a specific color.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnExitMouseEntered
    /**
     * Handles the event when the mouse exits the exit button. Changes the
     * background color of the exit button back to its default color.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnExitMouseExited
    /**
     * Handles the event when the exit button is clicked. Exits the application.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent triggering this method.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);//exit the system
    }//GEN-LAST:event_btnExitActionPerformed
    /**
     * Handles the event when the manager button is clicked. Opens the Add
     * Manager window and hides the current window.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent triggering this method.
     */
    private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed

        //Open Main Add Manager Frame
        AddManager addManager = new AddManager();

        addManager.setVisible(true);//show the main menu window
        setVisible(false);//hide the current window
    }//GEN-LAST:event_btnManagerActionPerformed
    /**
     * Handles the event when the player button is clicked. Opens the Add Player
     * window and hides the current window.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent triggering this method.
     */
    private void btnPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerActionPerformed
        //Open Main Add Manager Frame
        AddPlayer addPlayer = new AddPlayer();
        addPlayer.setVisible(true);//show the main menu window
        setVisible(false);//hide the current window
    }//GEN-LAST:event_btnPlayerActionPerformed

    /**
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMemberMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMemberMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMemberMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMemberMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMemberMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnManager;
    private javax.swing.JButton btnPlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel memberImg;
    // End of variables declaration//GEN-END:variables
}
