/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.Player;
import Logic.SportsLeagueSystem;
import static Logic.SportsLeagueSystem.removePlayerFromTeam;
import Logic.Team;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 * This class represents the GUI for adding player in a sports league system. It
 * allows users to add a player to the system and assign him/her to a team It
 * also provides options to navigate back to the add member menu or exit the
 * application.
 *
 * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
 */
public class AddPlayer extends javax.swing.JFrame {

    /**
     * Creates new form AddPlayer
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    public AddPlayer() {
        initComponents();
        noButton.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        managerNameLbl2 = new javax.swing.JLabel();
        captainGroup = new javax.swing.ButtonGroup();
        managerNameLbl6 = new javax.swing.JLabel();
        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        addManagerLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnBack1 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        isCaptainLbl = new javax.swing.JLabel();
        noButton = new javax.swing.JRadioButton();
        yesButton = new javax.swing.JRadioButton();
        fieldPositionLbl = new javax.swing.JLabel();
        fieldPositionBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        playerNameLbl = new javax.swing.JLabel();
        playerNameText = new javax.swing.JTextField();
        playerAddressLbl = new javax.swing.JLabel();
        playerAddressText = new javax.swing.JTextField();
        dateOfBirthLbl = new javax.swing.JLabel();
        dateOfBirthChooser = new com.toedter.calendar.JDateChooser();
        nationalityLbl = new javax.swing.JLabel();
        nationalityText = new javax.swing.JTextField();
        addressLblErr = new javax.swing.JLabel();
        nameLblErr = new javax.swing.JLabel();
        dateLblErr = new javax.swing.JLabel();
        nationalityLblErr = new javax.swing.JLabel();

        btnBack.setBackground(new java.awt.Color(221, 190, 169));
        btnBack.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        managerNameLbl2.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        managerNameLbl2.setForeground(new java.awt.Color(255, 232, 214));
        managerNameLbl2.setText("Player Address:");

        managerNameLbl6.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        managerNameLbl6.setForeground(new java.awt.Color(255, 232, 214));
        managerNameLbl6.setText("Is Captain");

        popupMenu1.setLabel("popupMenu1");
        popupMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupMenu1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1220, 630));

        jPanel1.setBackground(new java.awt.Color(107, 112, 92));
        jPanel1.setPreferredSize(new java.awt.Dimension(1220, 630));

        addManagerLbl.setFont(new java.awt.Font("Futura", 1, 48)); // NOI18N
        addManagerLbl.setForeground(new java.awt.Color(255, 232, 214));
        addManagerLbl.setText("Add Player");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/smallLogo.png"))); // NOI18N

        btnSubmit.setBackground(new java.awt.Color(221, 190, 169));
        btnSubmit.setFont(new java.awt.Font("Futura", 0, 20)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(107, 112, 92));

        btnBack1.setBackground(new java.awt.Color(221, 190, 169));
        btnBack1.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.setBorderPainted(false);
        btnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBack1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBack1MouseExited(evt);
            }
        });
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(221, 190, 169));
        btnExit.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(107, 112, 92));

        isCaptainLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        isCaptainLbl.setForeground(new java.awt.Color(255, 232, 214));
        isCaptainLbl.setText("Is Captain");

        captainGroup.add(noButton);
        noButton.setText("No");
        noButton.setActionCommand("False");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        captainGroup.add(yesButton);
        yesButton.setText("Yes");
        yesButton.setActionCommand("True");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        fieldPositionLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        fieldPositionLbl.setForeground(new java.awt.Color(255, 232, 214));
        fieldPositionLbl.setText("Field Position");

        fieldPositionBox.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        fieldPositionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Midfield", "Center", "Goal Keeper", "Defender" }));
        fieldPositionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPositionBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(fieldPositionLbl)
                        .addGap(18, 18, 18)
                        .addComponent(fieldPositionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(isCaptainLbl)
                        .addGap(84, 84, 84)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isCaptainLbl)
                    .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPositionLbl)
                    .addComponent(fieldPositionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(107, 112, 92));

        playerNameLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        playerNameLbl.setForeground(new java.awt.Color(255, 232, 214));
        playerNameLbl.setText("Player Name:");

        playerNameText.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        playerNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNameTextActionPerformed(evt);
            }
        });

        playerAddressLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        playerAddressLbl.setForeground(new java.awt.Color(255, 232, 214));
        playerAddressLbl.setText("Player Address:");

        playerAddressText.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        playerAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerAddressTextActionPerformed(evt);
            }
        });

        dateOfBirthLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        dateOfBirthLbl.setForeground(new java.awt.Color(255, 232, 214));
        dateOfBirthLbl.setText("Date of Birth:");

        dateOfBirthChooser.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N

        nationalityLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        nationalityLbl.setForeground(new java.awt.Color(255, 232, 214));
        nationalityLbl.setText("Nationality:");

        nationalityText.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        nationalityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityTextActionPerformed(evt);
            }
        });

        addressLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        addressLblErr.setForeground(new java.awt.Color(255, 0, 0));

        nameLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        nameLblErr.setForeground(new java.awt.Color(255, 0, 0));

        dateLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        dateLblErr.setForeground(new java.awt.Color(255, 0, 0));

        nationalityLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        nationalityLblErr.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerAddressLbl)
                    .addComponent(dateOfBirthLbl)
                    .addComponent(nationalityLbl)
                    .addComponent(playerNameLbl))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOfBirthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nationalityLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nationalityText, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerNameLbl)
                    .addComponent(playerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerAddressLbl)
                    .addComponent(playerAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addressLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOfBirthLbl)
                    .addComponent(dateOfBirthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationalityText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nationalityLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nationalityLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(589, 589, 589)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(344, 344, 344)
                                .addComponent(addManagerLbl)
                                .addGap(221, 221, 221)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addManagerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1220, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Handles the event when the mouse enters the back button. Changes the
     * background color of the back button to a specific color.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnBack1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseEntered
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnBack1MouseEntered
    /**
     * Handles the event when the mouse exits the back button. Changes the
     * background color of the back button back to its default color.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnBack1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseExited
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnBack1MouseExited
    /**
     * Handles the event when the back button is clicked. Opens the Add Member
     * Menu window and closes the current window.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent triggering this method.
     */
    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        AddMemberMenu addMember = new AddMemberMenu();
        addMember.setVisible(true); //show teams options window
        dispose(); //hide the current window
    }//GEN-LAST:event_btnBack1ActionPerformed
    /**
     * Handles the event when the mouse enters the exit button. Changes the
     * background color of the exit button to a specific color.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnExitMouseEntered
    /**
     * Handles the event when the mouse exits the exit button. Changes the
     * background color of the exit button back to its default color.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnExitMouseExited
    /**
     * Handles the event when the exit button is clicked. Exits the application.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent triggering this method.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);//exit the system
    }//GEN-LAST:event_btnExitActionPerformed

    private void nationalityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityTextActionPerformed

    private void btnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseEntered
        // TODO add your handling code here:
        btnSubmit.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnSubmitMouseEntered

    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        // TODO add your handling code here:
        btnSubmit.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnSubmitMouseExited
    /**
     * Handles the event when the submit button is clicked. Validates player
     * information and adds the player to a team or as an unassigned player.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent triggering this method.
     */
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        //sets the text fields to null     
        boolean submit = true;
        nameLblErr.setText(null);
        addressLblErr.setText(null);
        nationalityLblErr.setText(null);
        dateLblErr.setText(null);
        //creates variables for the text inserted
        String fieldPosition = (String) fieldPositionBox.getSelectedItem();
        String playerName = playerNameText.getText();
        String playerAddress = playerAddressText.getText();
        String nationality = nationalityText.getText();

        // Check if the isCaptain choice selected by the user is true or false
        boolean captain = yesButton.isSelected();

        // Check if any field is blank or less than 3 characters
        if (playerName.isEmpty() || playerName.length() < 3) {
            nameLblErr.setText(playerName.isEmpty() ? "Player Name cannot be blank" : "Player Name must be at least 3 characters");
            submit = false;
        }

        if (playerAddress.isEmpty() || playerAddress.length() < 10) {
            addressLblErr.setText(playerAddress.isEmpty() ? "Player Address cannot be blank" : "Player Address must be at least 10 characters");
            submit = false;
        }

        Date dob = dateOfBirthChooser.getDate();
        // Check if the date of birth is null
        if (dob == null) {
            dateLblErr.setText("Player Date of Birth cannot be blank");
            submit = false;
        } else {
//         SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM dd, yyyy");
//    String dobStr = dateFormat.format(dob);
            // Get the current date
            Calendar currentDate = Calendar.getInstance();

            // Subtract 15 years from the current date
            currentDate.add(Calendar.YEAR, -15);

            // Compare the date of birth with currentDate - 15 years
            Calendar dobCalendar = Calendar.getInstance();
            dobCalendar.setTime(dob);

            if (!dobCalendar.before(currentDate)) {
                submit = false;
                dateLblErr.setText("The player is not more than 15 years old.");
            }
        }

        if (nationality.isEmpty() || nationality.length() < 3) {
            nationalityLblErr.setText(nationality.isEmpty() ? "Nationality cannot be blank" : "Nationality must be at least 3 digits");
            submit = false;
        }

        // Check if player name or player nationality contains numbers
        Pattern pattern = Pattern.compile(".*\\d+.*"); // Pattern to match any digit
        Matcher matcherPlayerName = pattern.matcher(playerName);
        Matcher matcherPlayerNationality = pattern.matcher(nationality);

        if (matcherPlayerName.find()) {
            nameLblErr.setText("Player Name cannot contain numbers");
            submit = false;
        }

        if (matcherPlayerNationality.find()) {
            nationalityLblErr.setText("Player Nationality cannot contain numbers");
            submit = false;
        }

        if (submit) {
            if (dob != null) {
                Integer playerId = SportsLeagueSystem.getPlayersIds() + 1;
                SimpleDateFormat dateFormat = new SimpleDateFormat("d/M/yyy");
                String dobStr = dateFormat.format(dob);
                int choice = JOptionPane.showOptionDialog(
                        null,
                        "Do you want to assign player to team?",
                        "Confirmation",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null, // icon
                        new String[]{"Yes", "No"},
                        "Yes" // default button
                );

                if (choice == JOptionPane.YES_OPTION) {

                    // If user chooses "Yes", perform action
                    JComboBox<String> comboBox = new JComboBox<>();
                    ArrayList<Team> teamsList = SportsLeagueSystem.getTeamsList();
                    if (teamsList.size() == 0) {
                        JOptionPane.showMessageDialog(this, "No teams found, the player will be added as unassigned player");
                        //add player as unassigned 
                        SportsLeagueSystem.addUnassignedPlayerMember(playerId, playerName, playerAddress, dobStr, nationality, fieldPosition, captain);
                        MembersOptions mo = new MembersOptions();
                        mo.setVisible(true);
                        dispose();
                    } else {
                        for (Team team : teamsList) {
                            comboBox.addItem("Name: " + team.getTeamName() + " - ID: " + team.getTeamId());
                        }
                        int choice1 = JOptionPane.showConfirmDialog(this, comboBox, "Select Team", JOptionPane.OK_CANCEL_OPTION);
                        if (choice == JOptionPane.OK_OPTION) {
                            String selectedItem = (String) comboBox.getSelectedItem();
                            if (selectedItem != null) {
                                // Extract team ID only the number from the selected item
                                String[] parts = selectedItem.split("- ID:"); // Split the string based on "- ID:"

                                if (parts.length == 2) {
                                    String teamIdStr = parts[1].trim(); // Get the second part and remove leading/trailing spaces

                                    int teamId = Integer.parseInt(teamIdStr); // Parse the team ID
                                    System.out.println("team ID ---: " + teamId);

//if ok was clicked 
                                    if (choice1 == JOptionPane.OK_OPTION) {

                                        // Get salary input
                                        String salary = JOptionPane.showInputDialog(this, "Enter Salary:", "Salary", JOptionPane.OK_CANCEL_OPTION);

// If Cancel is clicked, salary will be null, and we should do nothing
                                        if (salary != null) {
                                            // If OK is clicked but salary is empty
                                            if (salary.isEmpty()) {
                                                JOptionPane.showMessageDialog(this, "Salary cannot be null.");
                                            } else {
                                                // Proceed with parsing and further checks
                                                try {
                                                    double salaryDouble = Double.parseDouble(salary);
                                                    if (salaryDouble == 0.0) {
                                                        JOptionPane.showMessageDialog(this, "Salary cannot be zero.");
                                                    } else if (salaryDouble < 400) {
                                                        JOptionPane.showMessageDialog(this, "Salary cannot be less than 400!");
                                                    } else {
                                                        // Check if the team has a captain
                                                        boolean found = false;
                                                        for (Player player : SportsLeagueSystem.searchTeam(teamId).getTeamPlayers()) {
                                                            if (player.isCaptain()) {
                                                                found = true;
                                                            }
                                                        }

                                                        if (found && captain == true) {
                                                            JOptionPane.showMessageDialog(this, "Player cannot be assigned as team captain. To change the team captain go to (Main Menu> Teams> Designate Player As Team Captain). ");
                                                            SportsLeagueSystem.searchTeam(teamId).getTeamPlayers().add(SportsLeagueSystem.addPlayerMember(playerId, playerName, playerAddress, dobStr, nationality, salaryDouble, fieldPosition, false));
                                                        } else {
                                                            // Add the player to the team 
                                                            SportsLeagueSystem.searchTeam(teamId).getTeamPlayers().add(SportsLeagueSystem.addPlayerMember(playerId, playerName, playerAddress, dobStr, nationality, salaryDouble, fieldPosition, captain));
                                                        }

                                                        // Success message 
                                                        JOptionPane.showMessageDialog(this, "The player has been added successfully!");
                                                        MembersOptions mo = new MembersOptions();
                                                        mo.setVisible(true);
                                                        dispose();
                                                    }
                                                } catch (NumberFormatException ex) {
                                                    JOptionPane.showMessageDialog(this, "Invalid salary format. Please enter a valid number.");
                                                }
                                            }
                                        }
                                    }
                                }
                            }

                        }
                    }
                } else if (choice == JOptionPane.NO_OPTION) {
                    //adding the player as unassigned 
                    //add player as unassigned 
                    SportsLeagueSystem.addUnassignedPlayerMember(playerId, playerName, playerAddress, dobStr, nationality, fieldPosition, captain);
                    JOptionPane.showMessageDialog(this, "The player has been added successfully!");
                    MembersOptions mo = new MembersOptions();
                    mo.setVisible(true);
                    dispose();

                }
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void playerNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerNameTextActionPerformed

    private void playerAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerAddressTextActionPerformed

    private void fieldPositionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPositionBoxActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_fieldPositionBoxActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noButtonActionPerformed

    private void popupMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popupMenu1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //        AddMember addMember = new AddMember();
        //        addMember.show(); //show teams options window
        //        dispose(); //hide the current window
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnBackMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addManagerLbl;
    private javax.swing.JLabel addressLblErr;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup captainGroup;
    private javax.swing.JLabel dateLblErr;
    private com.toedter.calendar.JDateChooser dateOfBirthChooser;
    private javax.swing.JLabel dateOfBirthLbl;
    private javax.swing.JComboBox<String> fieldPositionBox;
    private javax.swing.JLabel fieldPositionLbl;
    private javax.swing.JLabel isCaptainLbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel managerNameLbl2;
    private javax.swing.JLabel managerNameLbl6;
    private javax.swing.JLabel nameLblErr;
    private javax.swing.JLabel nationalityLbl;
    private javax.swing.JLabel nationalityLblErr;
    private javax.swing.JTextField nationalityText;
    private javax.swing.JRadioButton noButton;
    private javax.swing.JLabel playerAddressLbl;
    private javax.swing.JTextField playerAddressText;
    private javax.swing.JLabel playerNameLbl;
    private javax.swing.JTextField playerNameText;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JRadioButton yesButton;
    // End of variables declaration//GEN-END:variables
}
