/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.SportsLeagueSystem;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import Logic.*;
import java.util.ArrayList;

/**
 * The AlterTeamForm class represents the GUI form for altering team
 * information. This form allows users to modify team name, stadium name, and
 * stadium capacity.
 *
 * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
 */
public class AlterTeamForm extends javax.swing.JFrame {
//    private Team team;
//    private static SportsLeagueSystem ss = new SportsLeagueSystem();

    TeamsOptions teamsOptionsScreen;
    Team tempTeam;

    /**
     * Name: AlterTeamForm Purpose/Description: Creates new form AlterTeamForm.
     * This constructor is used when the form is opened from another screen.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param teamsOptionsScreen The reference to the TeamsOptions screen.
     * @param tempTeam The temporary Team object to be altered.
     */
    public AlterTeamForm(TeamsOptions teamsOptionsScreen, Team tempTeam) {
        initComponents();
        this.teamsOptionsScreen = teamsOptionsScreen;
        this.tempTeam = tempTeam;
        alterTeamWindowOpened();
    }

    /**
     * Creates new form AlterTeamForm. This constructor is used when the form is
     * opened independently.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    public AlterTeamForm() {
        initComponents();
    }

    /**
     * Initializes the AlterTeamForm window with the current team's information.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    private void alterTeamWindowOpened() {
        textTeamName.setText(tempTeam.getTeamName());
        textStadiumName.setText(tempTeam.getStadiumName());
        textStadiumCapacity.setText(Integer.toString(tempTeam.getStadiumCapacity()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        lblAlterTeam = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblStadiumName = new javax.swing.JLabel();
        lblStadiumCapacity = new javax.swing.JLabel();
        lblTeamName = new javax.swing.JLabel();
        textStadiumName = new javax.swing.JTextField();
        textTeamName = new javax.swing.JTextField();
        textStadiumCapacity = new javax.swing.JTextField();
        stadiumNameLblErr = new javax.swing.JLabel();
        teamNameLblErr = new javax.swing.JLabel();
        satdiumCapacityLblErr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(107, 112, 92));

        btnBack.setBackground(new java.awt.Color(221, 190, 169));
        btnBack.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(221, 190, 169));
        btnExit.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/smallLogo.png"))); // NOI18N

        lblAlterTeam.setFont(new java.awt.Font("Futura", 1, 48)); // NOI18N
        lblAlterTeam.setForeground(new java.awt.Color(255, 232, 214));
        lblAlterTeam.setText("Alter Team");

        btnSubmit.setBackground(new java.awt.Color(221, 190, 169));
        btnSubmit.setFont(new java.awt.Font("Futura", 0, 20)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblStadiumName.setFont(new java.awt.Font("Futura", 0, 30)); // NOI18N
        lblStadiumName.setForeground(new java.awt.Color(255, 232, 214));
        lblStadiumName.setText("Stadium Name:");

        lblStadiumCapacity.setFont(new java.awt.Font("Futura", 0, 30)); // NOI18N
        lblStadiumCapacity.setForeground(new java.awt.Color(255, 232, 214));
        lblStadiumCapacity.setText("Stadium Capacity:");

        lblTeamName.setFont(new java.awt.Font("Futura", 0, 30)); // NOI18N
        lblTeamName.setForeground(new java.awt.Color(255, 232, 214));
        lblTeamName.setText("Team Name:");

        textStadiumName.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        textStadiumName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStadiumNameActionPerformed(evt);
            }
        });

        textTeamName.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        textTeamName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTeamNameActionPerformed(evt);
            }
        });

        textStadiumCapacity.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        textStadiumCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStadiumCapacityActionPerformed(evt);
            }
        });

        stadiumNameLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        stadiumNameLblErr.setForeground(new java.awt.Color(255, 0, 0));

        teamNameLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        teamNameLblErr.setForeground(new java.awt.Color(255, 0, 0));

        satdiumCapacityLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        satdiumCapacityLblErr.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStadiumName)
                    .addComponent(lblTeamName)
                    .addComponent(lblStadiumCapacity))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textStadiumCapacity, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(textStadiumName, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(textTeamName, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(stadiumNameLblErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(satdiumCapacityLblErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teamNameLblErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 214, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(497, 497, 497)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(logo)
                .addGap(294, 294, 294)
                .addComponent(lblAlterTeam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblAlterTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeamName))
                .addGap(3, 3, 3)
                .addComponent(teamNameLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textStadiumName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStadiumName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stadiumNameLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textStadiumCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStadiumCapacity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(satdiumCapacityLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1220, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Handles the action when the Back button is clicked. It shows the
     * TeamsOptions screen and hides the current window.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        TeamsOptions teamsOptions = new TeamsOptions();
        teamsOptions.setVisible(true); //show teams options window
        dispose(); //hide the current window          
    }//GEN-LAST:event_btnBackActionPerformed
    /**
     * Handles the action when the Submit button is clicked. It validates the
     * input fields and alters the team's information if valid.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        boolean submit = true;
        teamNameLblErr.setText(null);
        stadiumNameLblErr.setText(null);
        satdiumCapacityLblErr.setText(null);

        String teamName = textTeamName.getText();
        String stadiumName = textStadiumName.getText();
        String capacity = textStadiumCapacity.getText();

        // Check if any field is blank or less than 3 characters
        if (teamName.isEmpty() || teamName.length() < 3) {
            teamNameLblErr.setText(teamName.isEmpty() ? "Team Name cannot be blank" : "Team Name must be at least 3 characters");
            submit = false;
        }

        if (stadiumName.isEmpty() || stadiumName.length() < 3) {
            stadiumNameLblErr.setText(stadiumName.isEmpty() ? "Stadium Name cannot be blank" : "Stadium Name must be at least 3 characters");
            submit = false;
        }

        if (capacity.isEmpty() || capacity.length() < 3) {
            satdiumCapacityLblErr.setText(capacity.isEmpty() ? "Stadium Capacity cannot be blank" : "Stadium Capacity must be at least 3 digits");
            submit = false;
        }

        // Check if team name or stadium name contains numbers
        Pattern pattern = Pattern.compile(".*\\d+.*"); // Pattern to match any digit
        Matcher matcherTeamName = pattern.matcher(teamName);
        Matcher matcherStadiumName = pattern.matcher(stadiumName);

        if (matcherTeamName.find()) {
            teamNameLblErr.setText("Team Name cannot contain numbers");
            submit = false;
        }

        if (matcherStadiumName.find()) {
            stadiumNameLblErr.setText("Stadium Name cannot contain numbers");
            submit = false;
        }

        // Check if stadium capacity contains characters
        Pattern patternCapacity = Pattern.compile("\\D"); // Pattern to match any non-digit character
        Matcher matcherCapacity = patternCapacity.matcher(capacity);

        if (matcherCapacity.find()) {
            satdiumCapacityLblErr.setText("Stadium Capacity must be a number");
            submit = false;
        }

        if (submit) {
            try {
                int stadiumCapacity = Integer.parseInt(capacity);
                SportsLeagueSystem.alterTeam(tempTeam.getTeamId(), teamName, stadiumName, stadiumCapacity);
                JOptionPane.showMessageDialog(this, "The team information has been altered successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                dispose(); //hide the current screen 
                TeamsOptions teamsOptions = new TeamsOptions();
                teamsOptions.setVisible(true); //display teams options screen
                System.out.println("There are " + SportsLeagueSystem.getTeamsList().size());

            } catch (NumberFormatException ex) {
                satdiumCapacityLblErr.setText("Invalid stadium capacity");
            }
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void textStadiumNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStadiumNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStadiumNameActionPerformed

    private void textTeamNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTeamNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTeamNameActionPerformed

    private void textStadiumCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStadiumCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStadiumCapacityActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);//exit the system
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseEntered
        // TODO add your handling code here:
        btnSubmit.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnSubmitMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnBackMouseExited

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        // TODO add your handling code here:
        btnSubmit.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnSubmitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterTeamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterTeamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterTeamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterTeamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterTeamForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlterTeam;
    private javax.swing.JLabel lblStadiumCapacity;
    private javax.swing.JLabel lblStadiumName;
    private javax.swing.JLabel lblTeamName;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel satdiumCapacityLblErr;
    private javax.swing.JLabel stadiumNameLblErr;
    private javax.swing.JLabel teamNameLblErr;
    private javax.swing.JTextField textStadiumCapacity;
    private javax.swing.JTextField textStadiumName;
    private javax.swing.JTextField textTeamName;
    // End of variables declaration//GEN-END:variables
}
