/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.Manager;
import Logic.Member;
import Logic.Player;
import Logic.SportsLeagueSystem;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 * Represents the Alter Member Menu in the sports league system GUI. Allows
 * users to select either a Manager or a Player to alter their information.
 *
 * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
 */
public class AlterMemberMenu extends javax.swing.JFrame {

    /**
     * Creates new form AlterMemberM
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    @SuppressWarnings("unchecked")
    public AlterMemberMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnManager = new javax.swing.JButton();
        btnPlayer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1220, 630));
        setMinimumSize(new java.awt.Dimension(1220, 630));

        jPanel1.setBackground(new java.awt.Color(107, 112, 92));
        jPanel1.setMinimumSize(new java.awt.Dimension(1220, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1220, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/smallLogo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 232, 214));
        jLabel2.setText("Alter Member");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        btnBack1.setBackground(new java.awt.Color(221, 190, 169));
        btnBack1.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.setBorderPainted(false);
        btnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBack1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBack1MouseExited(evt);
            }
        });
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, 120, -1));

        btnExit.setBackground(new java.awt.Color(221, 190, 169));
        btnExit.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 70, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/manager.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 208, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/member.jpeg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 212, -1, -1));

        btnManager.setBackground(new java.awt.Color(221, 190, 169));
        btnManager.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManager.setText("Manager");
        btnManager.setMaximumSize(new java.awt.Dimension(75, 31));
        btnManager.setMinimumSize(new java.awt.Dimension(75, 31));
        btnManager.setPreferredSize(new java.awt.Dimension(75, 31));
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 508, 228, 44));

        btnPlayer.setBackground(new java.awt.Color(221, 190, 169));
        btnPlayer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPlayer.setText("Player");
        btnPlayer.setMaximumSize(new java.awt.Dimension(75, 31));
        btnPlayer.setMinimumSize(new java.awt.Dimension(75, 31));
        btnPlayer.setPreferredSize(new java.awt.Dimension(75, 31));
        btnPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 508, 228, 44));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1220, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1MouseEntered

    private void btnBack1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1MouseExited

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        MembersOptions membersOptions = new MembersOptions();
        membersOptions.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);//exit the system
    }//GEN-LAST:event_btnExitActionPerformed
    /**
     * Action performed event handler for the btnManager button. Handles button
     * click on the Manager button. Retrieves a list of assigned managers,
     * displays them in a combo box, and allows the user to select a manager for
     * alteration. If no managers are found, displays an error message.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent representing the button click event.
     */
    private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed
        JComboBox comboBox = new JComboBox();
        ArrayList<Member> assignedMembers = SportsLeagueSystem.getAssignedMembersList();
        int count = 0;
        for (Member member : assignedMembers) {
            if (member instanceof Manager) {
                count++;
            }
        }
        if (count == 0) {
            JOptionPane.showMessageDialog(this, "No managers found in the system!");
        } else {
            for (Member member : assignedMembers) {
                if (member instanceof Manager) {
                    Manager tempManager = (Manager) member;
                    comboBox.addItem("Name: " + tempManager.getMemberName() + " - ID: " + tempManager.getMemberId());
                }
            }
            int choice = JOptionPane.showConfirmDialog(this, comboBox, "Select Manager", JOptionPane.OK_CANCEL_OPTION);
            if (choice == JOptionPane.CANCEL_OPTION || choice == JOptionPane.CLOSED_OPTION) {// if clicked cancel or close
                this.setVisible(true); //display current window and hide the pop up
            } else {
                String selectedManager = (String) comboBox.getSelectedItem();
                // Extract the team ID from the selected item
               
                Integer managerId = Integer.parseInt(selectedManager.split(" - ID: ")[1]);

                if (managerId != null) {
                    //delete the manager from the team
                    AlterManager alterManager;
                    try {
                    
                        alterManager = new AlterManager(this, (Manager) SportsLeagueSystem.searchMember(managerId));
                        alterManager.setVisible(true);
                        dispose();

                    } catch (ParseException ex) {
                        Logger.getLogger(AlterMemberMenu.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }
    }//GEN-LAST:event_btnManagerActionPerformed
    /**
     * Action performed event handler for the btnPlayer button. Handles button
     * click on the Player button. Retrieves a list of assigned players and
     * unassigned players, displays them in a combo box, and allows the user to
     * select a player for alteration. If no players are found, displays an
     * error message.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent representing the button click event.
     */
    private void btnPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerActionPerformed
        JComboBox comboBox = new JComboBox();
        ArrayList<Member> assignedPlayers = SportsLeagueSystem.getAssignedMembersList();
        ArrayList<Player> unAssignedPlayers = SportsLeagueSystem.getUnAssignedPlayersList();
        int count = 0;

        for (Member member : assignedPlayers) {
            if (member instanceof Player) {
                count++;
            }
        }

        if (count == 0 && unAssignedPlayers.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No players found in the system!");
        } else {
            if (count != 0) {
                // Add the assigned players to the combo box
                for (Member member : assignedPlayers) {
                    if (member instanceof Player) {
                        Player tempPlayer = (Player) member;
                        comboBox.addItem("Name: " + tempPlayer.getMemberName() + " - ID: " + tempPlayer.getMemberId());
                    }
                }
            }

            // Add unassigned players to the combo box
            if (!unAssignedPlayers.isEmpty()) {
                for (Player player : unAssignedPlayers) {
                    comboBox.addItem("Name: " + player.getMemberName() + " - ID: " + player.getMemberId());
                }
            }

            int choice = JOptionPane.showConfirmDialog(this, comboBox, "Select Player", JOptionPane.OK_CANCEL_OPTION);

            if (choice == JOptionPane.CANCEL_OPTION || choice == JOptionPane.CLOSED_OPTION) {
                this.setVisible(true); // Display current window and hide the pop up
            } else {
                String selectedPlayer = (String) comboBox.getSelectedItem();
                // Extract the player ID from the selected item
                Integer playerId = Integer.parseInt(selectedPlayer.split(" - ID: ")[1]);

                if (playerId != null) {

                    AlterPlayer alterPlayer;
                    try {
                        alterPlayer = new AlterPlayer(this, (Player) SportsLeagueSystem.searchMember(playerId));
                        alterPlayer.setVisible(true);
                        dispose();
                    } catch (ParseException ex) {
                        Logger.getLogger(AlterMemberMenu.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }
    }//GEN-LAST:event_btnPlayerActionPerformed

    /**
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterMemberMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterMemberMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterMemberMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterMemberMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterMemberMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnManager;
    private javax.swing.JButton btnPlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
