/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.Player;
import Logic.SportsLeagueSystem;
import Logic.Team;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 * This class represents the Alter Player form in the GUI of the sports league
 * system. It allows users to modify player information such as name, address,
 * date of birth, nationality, field position, and captain status. The form
 * includes data validation, event handling, and interaction with the
 * SportsLeagueSystem logic.
 *
 * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
 */
public class AlterPlayer extends javax.swing.JFrame {

    private AlterMemberMenu alterMemberMenu;// Reference to the AlterMemberMenu for navigation
    private Player tempPlayer;// Temporary storage for the player being modified

    /**
     * Creates new form AlterPlayer. Initializes the AlterPlayer form and its
     * components.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    public AlterPlayer() {
        initComponents();

    }

    /**
     * Name: AlterPlayer Purpose/Description: Constructor with parameters.
     * Creates a new AlterPlayer form with specified AlterMemberMenu and Player.
     * Initializes the form and populates it with the player's current
     * information.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param alterMemberMenu The AlterMemberMenu instance for navigation.
     * @param tempPlayer The Player object to be modified.
     * @throws ParseException If there's an error in parsing dates.
     */
    public AlterPlayer(AlterMemberMenu alterMemberMenu, Player tempPlayer) throws ParseException {
        initComponents();
        this.alterMemberMenu = alterMemberMenu;
        this.tempPlayer = tempPlayer;
        alterPlayerWindowOpened();
    }

    /**
     * Method called when the AlterPlayer window is opened. Populates the form
     * with the player's current information. Handles date parsing and sets up
     * radio buttons, text fields, and combo boxes.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @throws ParseException If there's an error in parsing dates.
     */
    private void alterPlayerWindowOpened() throws ParseException {
        playerNameText.setText(tempPlayer.getMemberName());
        playerAddressText.setText(tempPlayer.getMemberAddress());

        String dobString = tempPlayer.getDateOfBirth();
        Date date = new SimpleDateFormat("d/M/yyy").parse(dobString);
        dateOfBirthChooser.setDate(date);

        nationalityText.setText(tempPlayer.getNationality());
        if (tempPlayer.isCaptain()) {
            yesButton.setSelected(true);
        } else {
            noButton.setSelected(true);
        }

        fieldPositionBox.setSelectedItem(tempPlayer.getFieldPosition());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        captainGroup = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        alterManagerLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        isCaptainLbl = new javax.swing.JLabel();
        noButton = new javax.swing.JRadioButton();
        yesButton = new javax.swing.JRadioButton();
        fieldPositionLbl = new javax.swing.JLabel();
        fieldPositionBox = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        playerNameLbl = new javax.swing.JLabel();
        playerNameText = new javax.swing.JTextField();
        playerAddressLbl = new javax.swing.JLabel();
        playerAddressText = new javax.swing.JTextField();
        dateOfBirthLbl = new javax.swing.JLabel();
        dateOfBirthChooser = new com.toedter.calendar.JDateChooser();
        nationalityLbl = new javax.swing.JLabel();
        nationalityText = new javax.swing.JTextField();
        addressLblErr = new javax.swing.JLabel();
        nameLblErr = new javax.swing.JLabel();
        dateLblErr = new javax.swing.JLabel();
        nationalityLblErr = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(107, 112, 92));
        jPanel5.setPreferredSize(new java.awt.Dimension(1220, 630));

        alterManagerLbl.setFont(new java.awt.Font("Futura", 1, 48)); // NOI18N
        alterManagerLbl.setForeground(new java.awt.Color(255, 232, 214));
        alterManagerLbl.setText("Alter Player");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/smallLogo.png"))); // NOI18N

        btnSubmit.setBackground(new java.awt.Color(221, 190, 169));
        btnSubmit.setFont(new java.awt.Font("Futura", 0, 20)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(107, 112, 92));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(107, 112, 92));

        isCaptainLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        isCaptainLbl.setForeground(new java.awt.Color(255, 232, 214));
        isCaptainLbl.setText("Is Captain");

        captainGroup.add(noButton);
        noButton.setText("No");
        noButton.setActionCommand("False");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        captainGroup.add(yesButton);
        yesButton.setText("Yes");
        yesButton.setActionCommand("True");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        fieldPositionLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        fieldPositionLbl.setForeground(new java.awt.Color(255, 232, 214));
        fieldPositionLbl.setText("Field Position");

        fieldPositionBox.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        fieldPositionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Midfield", "Center", "Goal Keeper", "Defender" }));
        fieldPositionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPositionBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(fieldPositionLbl)
                        .addGap(18, 18, 18)
                        .addComponent(fieldPositionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(isCaptainLbl)
                        .addGap(84, 84, 84)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isCaptainLbl)
                    .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPositionLbl)
                    .addComponent(fieldPositionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(107, 112, 92));

        playerNameLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        playerNameLbl.setForeground(new java.awt.Color(255, 232, 214));
        playerNameLbl.setText("Player Name:");

        playerNameText.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        playerNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNameTextActionPerformed(evt);
            }
        });

        playerAddressLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        playerAddressLbl.setForeground(new java.awt.Color(255, 232, 214));
        playerAddressLbl.setText("Player Address:");

        playerAddressText.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        playerAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerAddressTextActionPerformed(evt);
            }
        });

        dateOfBirthLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        dateOfBirthLbl.setForeground(new java.awt.Color(255, 232, 214));
        dateOfBirthLbl.setText("Date of Birth:");

        dateOfBirthChooser.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N

        nationalityLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        nationalityLbl.setForeground(new java.awt.Color(255, 232, 214));
        nationalityLbl.setText("Nationality:");

        nationalityText.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        nationalityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityTextActionPerformed(evt);
            }
        });

        addressLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        addressLblErr.setForeground(new java.awt.Color(255, 0, 0));

        nameLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        nameLblErr.setForeground(new java.awt.Color(255, 0, 0));

        dateLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        dateLblErr.setForeground(new java.awt.Color(255, 0, 0));

        nationalityLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        nationalityLblErr.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerAddressLbl)
                    .addComponent(dateOfBirthLbl)
                    .addComponent(nationalityLbl)
                    .addComponent(playerNameLbl))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOfBirthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nationalityLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nationalityText, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerNameLbl)
                    .addComponent(playerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerAddressLbl)
                    .addComponent(playerAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addressLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOfBirthLbl)
                    .addComponent(dateOfBirthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationalityText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nationalityLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nationalityLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnBack.setBackground(new java.awt.Color(221, 190, 169));
        btnBack.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(221, 190, 169));
        btnExit.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(284, 284, 284)
                                .addComponent(alterManagerLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(alterManagerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1220, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseEntered
        // TODO add your handling code here:
        btnSubmit.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnSubmitMouseEntered

    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        // TODO add your handling code here:
        btnSubmit.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnSubmitMouseExited
    /**
     * Event handler for the Submit button in the AlterPlayer form. Performs
     * data validation and submits the modified player information to the
     * system.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent representing the button click event.
     */
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
         boolean submit = true;
    nameLblErr.setText(null);
    addressLblErr.setText(null);
    nationalityLblErr.setText(null);
    dateLblErr.setText(null);
    String fieldPosition = (String) fieldPositionBox.getSelectedItem();
    String playerName = playerNameText.getText();
    String playerAddress = playerAddressText.getText();
    String nationality = nationalityText.getText();

    boolean captain = yesButton.isSelected();
    boolean captain2 = captain;

    if (playerName.isEmpty() || playerName.length() < 3) {
        nameLblErr.setText(playerName.isEmpty() ? "Player Name cannot be blank" : "Player Name must be at least 3 characters");
        submit = false;
    }

    if (playerAddress.isEmpty() || playerAddress.length() < 10) {
        addressLblErr.setText(playerAddress.isEmpty() ? "Player Address cannot be blank" : "Player Address must be at least 10 characters");
        submit = false;
    }

    Date dob = dateOfBirthChooser.getDate();
    if (dob == null) {
        dateLblErr.setText("Player Date of Birth cannot be blank");
        submit = false;
    } else {
        Calendar currentDate = Calendar.getInstance();
        currentDate.add(Calendar.YEAR, -15);
        Calendar dobCalendar = Calendar.getInstance();
        dobCalendar.setTime(dob);
        if (!dobCalendar.before(currentDate)) {
            submit = false;
            dateLblErr.setText("The player is not more than 15 years old.");
        }
    }

    if (nationality.isEmpty() || nationality.length() < 3) {
        nationalityLblErr.setText(nationality.isEmpty() ? "Nationality cannot be blank" : "Nationality must be at least 3 characters");
        submit = false;
    }

    Pattern pattern = Pattern.compile(".*\\d+.*");
    Matcher matcherPlayerName = pattern.matcher(playerName);
    Matcher matcherPlayerNationality = pattern.matcher(nationality);

    if (matcherPlayerName.find()) {
        nameLblErr.setText("Player Name cannot contain numbers");
        submit = false;
    }

    if (matcherPlayerNationality.find()) {
        nationalityLblErr.setText("Player Nationality cannot contain numbers");
        submit = false;
    }

    if (submit) {
        if (dob != null && tempPlayer != null) {
            int playerId = tempPlayer.getMemberId();
            SimpleDateFormat dateFormat = new SimpleDateFormat("d/M/yyyy");
            String dobStr = dateFormat.format(dob);
            boolean found = false;
            int teamId = -2;
            for (Team team : SportsLeagueSystem.getTeamsList()) {
                for (Player player : team.getTeamPlayers()) {
                    if (playerId == player.getMemberId()) {
                        found = true;
                        teamId = team.getTeamId();
                        break;
                    }
                }
            }

            if (found) {
                boolean found1 = false;
                Player tempP = null;
                for (Player player : SportsLeagueSystem.searchTeam(teamId).getTeamPlayers()) {
                    if (player.isCaptain()) {
                        found1 = true;
                        tempP = player;
                        break;
                    }
                }

                if (found1 && captain2 && tempPlayer.getMemberId() != tempP.getMemberId()) {
                    JOptionPane.showMessageDialog(this, "The team already has a captain. Player cannot be altered to be captain since there is already a captain for this team.");
                    captain2 = false;
                }

                if (!captain2 && tempP != null && tempPlayer.getMemberId() == tempP.getMemberId()) {
                    captain2 = false;
                }

                int choice = JOptionPane.showOptionDialog(this, "Do you want to update the player salary?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
                if (choice == JOptionPane.YES_OPTION) {
                    String salary = JOptionPane.showInputDialog(this, "Enter Salary:", "Salary", JOptionPane.OK_CANCEL_OPTION);
                    if (salary != null) {
                        if (salary.isEmpty()) {
                            JOptionPane.showMessageDialog(this, "Salary cannot be null.");
                        } else {
                            try {
                                double salaryDouble = Double.parseDouble(salary);
                                if (salaryDouble == 0.0) {
                                    JOptionPane.showMessageDialog(this, "Salary cannot be zero.");
                                } else if (salaryDouble < 400) {
                                    JOptionPane.showMessageDialog(this, "Salary cannot be less than 400!");
                                } else {
                                    SportsLeagueSystem.searchMember(playerId).setYearlySalary(salaryDouble);
                                    SportsLeagueSystem.alterPlayerMember(playerId, fieldPosition, captain2, playerName, playerAddress, dobStr, nationality);
                                    JOptionPane.showMessageDialog(this, "The player information has been altered successfully!");
                                    MembersOptions mo = new MembersOptions();
                                    mo.setVisible(true);
                                    dispose();
                                }
                            } catch (NumberFormatException ex) {
                                JOptionPane.showMessageDialog(this, "Invalid salary format. Please enter a valid number.");
                            }
                        }
                    }
                } else if (choice == JOptionPane.NO_OPTION) {
                    SportsLeagueSystem.alterPlayerMember(playerId, fieldPosition, captain2, playerName, playerAddress, dobStr, nationality);
                    JOptionPane.showMessageDialog(this, "The player information has been altered successfully!");
                    MembersOptions mo = new MembersOptions();
                    mo.setVisible(true);
                    dispose();
                }
            } else {
                SportsLeagueSystem.alterPlayerMember(playerId, fieldPosition, captain2, playerName, playerAddress, dobStr, nationality);
                JOptionPane.showMessageDialog(this, "The player information has been altered successfully!");
                MembersOptions mo = new MembersOptions();
                mo.setVisible(true);
                dispose();
            }
        }
    }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AlterMemberMenu alterMemberMenu = new AlterMemberMenu();
        alterMemberMenu.setVisible(true);
        dispose(); //hide the current window
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);//exit the system
    }//GEN-LAST:event_btnExitActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noButtonActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesButtonActionPerformed

    private void fieldPositionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPositionBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_fieldPositionBoxActionPerformed

    private void playerNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerNameTextActionPerformed

    private void playerAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerAddressTextActionPerformed

    private void nationalityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLblErr;
    private javax.swing.JLabel alterManagerLbl;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup captainGroup;
    private javax.swing.JLabel dateLblErr;
    private com.toedter.calendar.JDateChooser dateOfBirthChooser;
    private javax.swing.JLabel dateOfBirthLbl;
    private javax.swing.JComboBox<String> fieldPositionBox;
    private javax.swing.JLabel fieldPositionLbl;
    private javax.swing.JLabel isCaptainLbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel nameLblErr;
    private javax.swing.JLabel nationalityLbl;
    private javax.swing.JLabel nationalityLblErr;
    private javax.swing.JTextField nationalityText;
    private javax.swing.JRadioButton noButton;
    private javax.swing.JLabel playerAddressLbl;
    private javax.swing.JTextField playerAddressText;
    private javax.swing.JLabel playerNameLbl;
    private javax.swing.JTextField playerNameText;
    private javax.swing.JRadioButton yesButton;
    // End of variables declaration//GEN-END:variables
}
