/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import Logic.*;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 * This class represents the GUI for alter manager in a sports league system. It
 * allows users to alter a manager that exists in the system It also provides
 * options to navigate back to the alter member menu or exit the application.
 *
 * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
 * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
 */
public class AlterManager extends javax.swing.JFrame {

    AlterMemberMenu alterMemberMenu;
    Manager tempManager;

    /**
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param alterMemberMenu
     * @param tempManager
     * @throws ParseException
     */
    public AlterManager(AlterMemberMenu alterMemberMenu, Manager tempManager) throws ParseException {
        initComponents();
        this.alterMemberMenu = alterMemberMenu;
        this.tempManager = tempManager;
        alterManagerWindowOpened();
    }

    /**
     * // * Creates new form
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    public AlterManager() {
        initComponents();
    }

    //display the stored infromation of the chosen manager in the text fields
    private void alterManagerWindowOpened() throws ParseException {
        managerNameText.setText(tempManager.getMemberName());
        managerAddressText.setText(tempManager.getMemberAddress());

        String dobString = tempManager.getDateOfBirth();
        Date date = new SimpleDateFormat("d/M/yyy").parse(dobString);
        dateOfBirthChooser.setDate(date);

        nationalityText.setText(tempManager.getNationality());
        String salary = Double.toString(tempManager.getYearlySalary());
        managerSalaryText.setText(salary);
        String bonus = Double.toString(tempManager.getBonusPercentage());
        managerBonusText.setText(bonus);
        managerQualificationsText.setText(tempManager.getCoachingQualifications());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addManagerLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        yearlySalaryText = new javax.swing.JTextField();
        bonusPercentageText = new javax.swing.JTextField();
        coachingQualificationsText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        managerNameLbl = new javax.swing.JLabel();
        managerNameText = new javax.swing.JTextField();
        managerAddressLbl = new javax.swing.JLabel();
        nationalityLbl = new javax.swing.JLabel();
        nationalityText = new javax.swing.JTextField();
        dateOfBirthLbl = new javax.swing.JLabel();
        managerAddressText = new javax.swing.JTextField();
        nameLblErr = new javax.swing.JLabel();
        dateLblErr = new javax.swing.JLabel();
        nationalityLblErr = new javax.swing.JLabel();
        addressLblErr = new javax.swing.JLabel();
        dateOfBirthChooser = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        yearlySalaryLbl = new javax.swing.JLabel();
        coachingLbl = new javax.swing.JLabel();
        managerNameText3 = new javax.swing.JTextField();
        managerSalaryText = new javax.swing.JTextField();
        bonusPercentageLbl = new javax.swing.JLabel();
        qualificationsLblErr = new javax.swing.JLabel();
        managerQualificationsText = new javax.swing.JTextField();
        salaryLblErr = new javax.swing.JLabel();
        coachingLbl1 = new javax.swing.JLabel();
        managerBonusText = new javax.swing.JTextField();
        bonusLblErr = new javax.swing.JLabel();
        managerNameText1 = new javax.swing.JTextField();
        managerNameText2 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1220, 630));

        jPanel1.setBackground(new java.awt.Color(107, 112, 92));
        jPanel1.setMaximumSize(new java.awt.Dimension(1220, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1220, 630));

        addManagerLbl.setFont(new java.awt.Font("Futura", 1, 48)); // NOI18N
        addManagerLbl.setForeground(new java.awt.Color(255, 232, 214));
        addManagerLbl.setText("Alter Manager");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/smallLogo.png"))); // NOI18N

        btnSubmit.setBackground(new java.awt.Color(221, 190, 169));
        btnSubmit.setFont(new java.awt.Font("Futura", 0, 20)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        yearlySalaryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearlySalaryTextActionPerformed(evt);
            }
        });

        bonusPercentageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonusPercentageTextActionPerformed(evt);
            }
        });

        coachingQualificationsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachingQualificationsTextActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(107, 112, 92));

        managerNameLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        managerNameLbl.setForeground(new java.awt.Color(255, 232, 214));
        managerNameLbl.setText("Manager Name:");

        managerNameText.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        managerNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerNameTextActionPerformed(evt);
            }
        });

        managerAddressLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        managerAddressLbl.setForeground(new java.awt.Color(255, 232, 214));
        managerAddressLbl.setText("Manager Address:");

        nationalityLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        nationalityLbl.setForeground(new java.awt.Color(255, 232, 214));
        nationalityLbl.setText("Nationality:");

        nationalityText.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        nationalityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityTextActionPerformed(evt);
            }
        });

        dateOfBirthLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        dateOfBirthLbl.setForeground(new java.awt.Color(255, 232, 214));
        dateOfBirthLbl.setText("Date of Birth:");

        managerAddressText.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        managerAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerAddressTextActionPerformed(evt);
            }
        });

        nameLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        nameLblErr.setForeground(new java.awt.Color(255, 0, 0));

        dateLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        dateLblErr.setForeground(new java.awt.Color(255, 0, 0));

        nationalityLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        nationalityLblErr.setForeground(new java.awt.Color(255, 0, 0));

        addressLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        addressLblErr.setForeground(new java.awt.Color(255, 0, 0));

        dateOfBirthChooser.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(managerNameLbl)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(managerAddressLbl)
                                    .addComponent(nationalityLbl)
                                    .addComponent(dateOfBirthLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateOfBirthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nationalityText, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(managerAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nationalityLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(managerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(managerNameLbl)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(managerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nameLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(managerAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(managerAddressLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dateOfBirthChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateOfBirthLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationalityLbl)
                    .addComponent(nationalityText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nationalityLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(107, 112, 92));

        yearlySalaryLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        yearlySalaryLbl.setForeground(new java.awt.Color(255, 232, 214));
        yearlySalaryLbl.setText("Yearly Salary:");

        coachingLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        coachingLbl.setForeground(new java.awt.Color(255, 232, 214));
        coachingLbl.setText("Coaching");

        managerNameText3.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        managerNameText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerNameText3ActionPerformed(evt);
            }
        });

        managerSalaryText.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        managerSalaryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerSalaryTextActionPerformed(evt);
            }
        });

        bonusPercentageLbl.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        bonusPercentageLbl.setForeground(new java.awt.Color(255, 232, 214));
        bonusPercentageLbl.setText("Bonus Percentage:");

        qualificationsLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        qualificationsLblErr.setForeground(new java.awt.Color(255, 0, 0));

        managerQualificationsText.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        managerQualificationsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerQualificationsTextActionPerformed(evt);
            }
        });

        salaryLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        salaryLblErr.setForeground(new java.awt.Color(255, 0, 0));

        coachingLbl1.setFont(new java.awt.Font("Futura", 0, 28)); // NOI18N
        coachingLbl1.setForeground(new java.awt.Color(255, 232, 214));
        coachingLbl1.setText("Qualifications:");

        managerBonusText.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        managerBonusText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerBonusTextActionPerformed(evt);
            }
        });

        bonusLblErr.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        bonusLblErr.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bonusPercentageLbl)
                            .addComponent(coachingLbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salaryLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(managerQualificationsText, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                    .addComponent(qualificationsLblErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(210, 210, 210)
                                .addComponent(managerNameText3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bonusLblErr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(managerBonusText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                            .addComponent(managerSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(yearlySalaryLbl)
                    .addComponent(coachingLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearlySalaryLbl)
                    .addComponent(managerSalaryText, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salaryLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bonusPercentageLbl)
                            .addComponent(managerBonusText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(coachingLbl)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(managerNameText3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(coachingLbl1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bonusLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(managerQualificationsText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qualificationsLblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        managerNameText1.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        managerNameText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerNameText1ActionPerformed(evt);
            }
        });

        managerNameText2.setFont(new java.awt.Font("Futura", 0, 16)); // NOI18N
        managerNameText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerNameText2ActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(221, 190, 169));
        btnBack.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(221, 190, 169));
        btnExit.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 98, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(yearlySalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bonusPercentageText, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(467, 467, 467)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(coachingQualificationsText, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(278, 278, 278)
                        .addComponent(addManagerLbl)
                        .addGap(282, 282, 282)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(1354, 1354, 1354)
                    .addComponent(managerNameText1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1355, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(1354, 1354, 1354)
                    .addComponent(managerNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1355, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addManagerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(yearlySalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(bonusPercentageText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coachingQualificationsText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(309, 309, 309)
                    .addComponent(managerNameText1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(328, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(309, 309, 309)
                    .addComponent(managerNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(328, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1658, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1220, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Handles the event when the mouse enters the submit button. Changes the
     * background color of the submit button.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseEntered
        // TODO add your handling code here:
        btnSubmit.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnSubmitMouseEntered
    /**
     * Handles the event when the mouse exits the submit button. Changes the
     * background color of the submit button.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        // TODO add your handling code here:
        btnSubmit.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnSubmitMouseExited
    /**
     * Handles the event when the submit button is clicked. Performs validation
     * checks on manager details and alters them if valid.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent triggering this method.
     */
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

//sets the text fields to null 
        boolean submit = true;
        nameLblErr.setText(null);
        addressLblErr.setText(null);
        dateLblErr.setText(null);
        nationalityLblErr.setText(null);
        salaryLblErr.setText(null);
        bonusLblErr.setText(null);
        qualificationsLblErr.setText(null);
//creates variables for the text inserted
        String managerName = managerNameText.getText();
        String managerAddress = managerAddressText.getText();
        String managerNationality = nationalityText.getText();
        String managerSalary = managerSalaryText.getText();
        String managerBonus = managerBonusText.getText();
        String managerQualifications = managerQualificationsText.getText();
        double salary = 0.0;
        double bonus = 0.0;
//checks that the data entered is not empty and within certain length
        if (managerName.isEmpty() || managerName.length() < 3) {
            nameLblErr.setText(managerName.isEmpty() ? "Manager Name cannot be blank" : "Manager Name must be at least 3 characters");
            submit = false;
        }

        if (managerAddress.isEmpty() || managerAddress.length() < 10) {
            addressLblErr.setText(managerAddress.isEmpty() ? "Manager Address cannot be blank" : "Manager Address must be at least 10 characters");
            submit = false;
        }

        if (managerNationality.isEmpty() || managerNationality.length() < 3) {
            nationalityLblErr.setText(managerNationality.isEmpty() ? "Manager Nationality cannot be blank" : "Nationality must be at least 3 characters");
            submit = false;
        }

        if (managerQualifications.isEmpty() || managerQualifications.length() < 8) {
            qualificationsLblErr.setText(managerQualifications.isEmpty() ? "Manager Qualification cannot be blank" : "Qualification must be at least 8 characters");
            submit = false;
        }

        if (managerSalary.isEmpty()) {
            salaryLblErr.setText("Manager Salary cannot be blank");
            submit = false;
        } else {
            try {
                salary = Double.parseDouble(managerSalary);
                if (salary < 400) {
                    salaryLblErr.setText("Manager Salary must be at least 400");
                    submit = false;
                }
            } catch (NumberFormatException e) {
                salaryLblErr.setText("Manager Salary must be a number");
                submit = false;
            }
        }

        if (managerBonus.isEmpty()) {
            bonusLblErr.setText("Manager Bonus cannot be blank");
            submit = false;
        } else {
            try {
                bonus = Double.parseDouble(managerBonus);
                if (bonus < 0) {
                    bonusLblErr.setText("Manager Bonus cannot be negative");
                    submit = false;
                }
            } catch (NumberFormatException e) {
                bonusLblErr.setText("Manager Bonus must be a number");
                submit = false;
            }
        }

        Date dob = dateOfBirthChooser.getDate();
        if (dob == null) {
            dateLblErr.setText("Manager Date of Birth cannot be blank");
            submit = false;
        } else {
            Calendar currentDate = Calendar.getInstance();
            currentDate.add(Calendar.YEAR, -15);
            Calendar dobCalendar = Calendar.getInstance();
            dobCalendar.setTime(dob);
            if (!dobCalendar.before(currentDate)) {
                submit = false;
                dateLblErr.setText("The manager is not more than 15 years old.");
            }
        }
// Check if manager name or manager nationality contains numbers
        Pattern pattern = Pattern.compile(".*\\d+.*");
        Matcher matcherManagerName = pattern.matcher(managerName);
        Matcher matcherManagerNationality = pattern.matcher(managerNationality);

        if (matcherManagerName.find()) {
            nameLblErr.setText("Manager Name cannot contain numbers");
            submit = false;
        }

        if (matcherManagerNationality.find()) {
            nationalityLblErr.setText("Manager Nationality cannot contain numbers");
            submit = false;
        }

        if (submit) {
            SimpleDateFormat sdf = new SimpleDateFormat("d/M/yyy");
            String dobString = sdf.format(dob);
            SportsLeagueSystem.alterManagerMember(tempManager.getMemberId(), bonus, managerQualifications, managerName, managerAddress, dobString, managerNationality, salary);
            JOptionPane.showMessageDialog(this, "The manager details have been altered successfully");
            MembersOptions membersOptions = new MembersOptions();
            membersOptions.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void nationalityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityTextActionPerformed

    private void yearlySalaryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearlySalaryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearlySalaryTextActionPerformed

    private void managerAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerAddressTextActionPerformed

    private void managerNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerNameTextActionPerformed

    private void bonusPercentageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonusPercentageTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bonusPercentageTextActionPerformed

    private void coachingQualificationsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachingQualificationsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachingQualificationsTextActionPerformed

    private void managerNameText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerNameText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerNameText1ActionPerformed

    private void managerNameText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerNameText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerNameText2ActionPerformed

    private void managerNameText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerNameText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerNameText3ActionPerformed

    private void managerSalaryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerSalaryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerSalaryTextActionPerformed

    private void managerQualificationsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerQualificationsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerQualificationsTextActionPerformed

    private void managerBonusTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerBonusTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerBonusTextActionPerformed
    /**
     * Handles the event when the mouse enters the back button. Changes the
     * background color of the back button.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnBackMouseEntered
    /**
     * Handles the event when the mouse exits the back button. Changes the
     * background color of the back button.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnBackMouseExited
    /**
     * Handles the event when the back button is clicked. Displays the
     * AlterMemberMenu window and hides the current window.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent triggering this method.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AlterMemberMenu alterMember = new AlterMemberMenu();
        alterMember.setVisible(true); //show teams options window
        dispose(); //hide the current window
    }//GEN-LAST:event_btnBackActionPerformed
    /**
     * Handles the event when the mouse enters the exit button. Changes the
     * background color of the exit button.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnExitMouseEntered
    /**
     * Handles the event when the mouse exits the exit button. Changes the
     * background color of the exit button.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The MouseEvent triggering this method.
     */
    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnExitMouseExited
    /**
     * Handles the event when the exit button is clicked. Exits the system.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param evt The ActionEvent triggering this method.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);//exit the system
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addManagerLbl;
    private javax.swing.JLabel addressLblErr;
    private javax.swing.JLabel bonusLblErr;
    private javax.swing.JLabel bonusPercentageLbl;
    private javax.swing.JTextField bonusPercentageText;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel coachingLbl;
    private javax.swing.JLabel coachingLbl1;
    private javax.swing.JTextField coachingQualificationsText;
    private javax.swing.JLabel dateLblErr;
    private com.toedter.calendar.JDateChooser dateOfBirthChooser;
    private javax.swing.JLabel dateOfBirthLbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel managerAddressLbl;
    private javax.swing.JTextField managerAddressText;
    private javax.swing.JTextField managerBonusText;
    private javax.swing.JLabel managerNameLbl;
    private javax.swing.JTextField managerNameText;
    private javax.swing.JTextField managerNameText1;
    private javax.swing.JTextField managerNameText2;
    private javax.swing.JTextField managerNameText3;
    private javax.swing.JTextField managerQualificationsText;
    private javax.swing.JTextField managerSalaryText;
    private javax.swing.JLabel nameLblErr;
    private javax.swing.JLabel nationalityLbl;
    private javax.swing.JLabel nationalityLblErr;
    private javax.swing.JTextField nationalityText;
    private javax.swing.JLabel qualificationsLblErr;
    private javax.swing.JLabel salaryLblErr;
    private javax.swing.JLabel yearlySalaryLbl;
    private javax.swing.JTextField yearlySalaryText;
    // End of variables declaration//GEN-END:variables
}
