/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.Manager;
import Logic.Member;
import Logic.Player;
import Logic.Team;
import java.util.ArrayList;

/**
 * This class represents a GUI window to display team members. It can display
 * both players and a team manager for a given team.
 *
 * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
 */
public class DisplayTeamMembers extends javax.swing.JFrame {

    private TeamsOptions teamsOptionsScreen;
    private Team tempTeam;
    private Team team;
    private TeamsOptions teamsOptions;

    /**
     * Name: DisplayTeamMembers Purpose/Description: Constructor to initialize
     * the DisplayTeamMembers window with a team and its members.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param teamsOptionsScreen The parent window (TeamsOptions) that opened
     * this window.
     * @param tempTeam The team whose members are to be displayed.
     */
    public DisplayTeamMembers(TeamsOptions teamsOptionsScreen, Team tempTeam) {
        initComponents();
        this.teamsOptionsScreen = teamsOptionsScreen;
        this.tempTeam = tempTeam;
        displayMembersWindowOpened();

    }

    /**
     * Name: Purpose/Description: Constructor to initialize the
     * DisplayTeamMembers window with a team and its members.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     * @param team The team whose members are to be displayed.
     * @param teamsOptions The parent window (TeamsOptions) that opened this
     * window.
     */
    public DisplayTeamMembers(Team team, TeamsOptions teamsOptions) {
        initComponents();
        this.team = team; // Update the team instance variable
        this.teamsOptions = teamsOptions;
        displayMembersWindowOpened();
    }

    /**
     * This method is called when the "displayMembers" window is opened. It
     * populates the display with information about team members, including the
     * team manager and players, along with their member IDs, names, roles,
     * annual pay, and captain status.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    private void displayMembersWindowOpened() {
        ArrayList<Player> playersList = team.getTeamPlayers();
        Manager teamManager = team.getTeamManager();
        String data;
        Player player;
        if (teamManager != null) {
            data = "Member ID: " + teamManager.getMemberId() + "\nMember Name: " + teamManager.getMemberName() + " - Manager" + "\nAnnual Pay: " + teamManager.getYearlySalary() + "BD" + "\n-------------------------\n";
            displayMembersTxt.append(data);
        }
        if (playersList.size() != 0) {
            for (int i = 0; i < playersList.size(); i++) {
                player = playersList.get(i);
                if (player.isCaptain()) {
                    data = "Member ID: " + player.getMemberId() + "\nMember Name: " + player.getMemberName() + " - Player is captain " + "\nAnnual Pay: " + player.getYearlySalary() + "BD" + "\n-------------------------\n";
                    displayMembersTxt.append(data);
                } else {
                    data = "Member ID: " + player.getMemberId() + "\nMember Name: " + player.getMemberName() + " - Player" + "\nAnnual Pay: " + player.getYearlySalary() + "BD" + "\n-------------------------\n";
                    displayMembersTxt.append(data);
                }

            }
        }

    }

    /**
     * Creates new form DisplayTeamMembersNew
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    public DisplayTeamMembers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayMembersTxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1220, 630));

        jPanel1.setBackground(new java.awt.Color(107, 112, 92));
        jPanel1.setPreferredSize(new java.awt.Dimension(1220, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/smallLogo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 232, 214));
        jLabel2.setText("Display Team Members");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        btnBack1.setBackground(new java.awt.Color(221, 190, 169));
        btnBack1.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.setBorderPainted(false);
        btnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBack1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBack1MouseExited(evt);
            }
        });
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 104, -1));

        btnExit.setBackground(new java.awt.Color(221, 190, 169));
        btnExit.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, 104, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 232, 214));
        jLabel3.setText("Team Members:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        displayMembersTxt.setBackground(new java.awt.Color(255, 232, 214));
        displayMembersTxt.setColumns(20);
        displayMembersTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        displayMembersTxt.setForeground(java.awt.Color.black);
        displayMembersTxt.setRows(5);
        jScrollPane2.setViewportView(displayMembersTxt);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 700, 348));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1220, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1MouseEntered

    private void btnBack1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1MouseExited

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        TeamsOptions to = new TeamsOptions();
        to.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);//exit the system
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * Main method to run the DisplayTeamMembers window.
     *
     * @param args The command line arguments.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayTeamMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayTeamMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayTeamMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayTeamMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayTeamMembers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnExit;
    private javax.swing.JTextArea displayMembersTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
