/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import Logic.*;

/**
 * This class represents the GUI for managing teams in a sports league system.
 * It allows users to add teams, alter team details, delete teams, display team
 * members, and designate a player as a team captain. It also provides options
 * to navigate back to the main menu or exit the application.
 *
 * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
 */
public class TeamsOptions extends javax.swing.JFrame {

    /**
     * Creates new form TeamsOptions
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    public TeamsOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAlterTeam = new javax.swing.JButton();
        btnAddTeam = new javax.swing.JButton();
        btnDispTeamMembers = new javax.swing.JButton();
        btnDesignatePlayer = new javax.swing.JButton();
        btnDeleteTeam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(107, 112, 92));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/team.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        btnBack.setBackground(new java.awt.Color(221, 190, 169));
        btnBack.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(221, 190, 169));
        btnExit.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Futura", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Teams");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Images/smallLogo.png"))); // NOI18N

        btnAlterTeam.setBackground(new java.awt.Color(221, 190, 169));
        btnAlterTeam.setFont(new java.awt.Font("Futura", 0, 20)); // NOI18N
        btnAlterTeam.setForeground(new java.awt.Color(0, 0, 0));
        btnAlterTeam.setText("Alter Team");
        btnAlterTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterTeamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterTeamMouseExited(evt);
            }
        });
        btnAlterTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterTeamActionPerformed(evt);
            }
        });

        btnAddTeam.setBackground(new java.awt.Color(221, 190, 169));
        btnAddTeam.setFont(new java.awt.Font("Futura", 0, 20)); // NOI18N
        btnAddTeam.setForeground(new java.awt.Color(0, 0, 0));
        btnAddTeam.setText("Add Team");
        btnAddTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddTeamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddTeamMouseExited(evt);
            }
        });
        btnAddTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeamActionPerformed(evt);
            }
        });

        btnDispTeamMembers.setBackground(new java.awt.Color(221, 190, 169));
        btnDispTeamMembers.setFont(new java.awt.Font("Futura", 0, 20)); // NOI18N
        btnDispTeamMembers.setForeground(new java.awt.Color(0, 0, 0));
        btnDispTeamMembers.setText("Display Team Members");
        btnDispTeamMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDispTeamMembersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDispTeamMembersMouseExited(evt);
            }
        });
        btnDispTeamMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDispTeamMembersActionPerformed(evt);
            }
        });

        btnDesignatePlayer.setBackground(new java.awt.Color(221, 190, 169));
        btnDesignatePlayer.setFont(new java.awt.Font("Futura", 0, 20)); // NOI18N
        btnDesignatePlayer.setForeground(new java.awt.Color(0, 0, 0));
        btnDesignatePlayer.setText("Designate Player As Team Captain");
        btnDesignatePlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDesignatePlayerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDesignatePlayerMouseExited(evt);
            }
        });
        btnDesignatePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesignatePlayerActionPerformed(evt);
            }
        });

        btnDeleteTeam.setBackground(new java.awt.Color(221, 190, 169));
        btnDeleteTeam.setFont(new java.awt.Font("Futura", 0, 20)); // NOI18N
        btnDeleteTeam.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteTeam.setText("Delete Team");
        btnDeleteTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteTeamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteTeamMouseExited(evt);
            }
        });
        btnDeleteTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(376, 376, 376)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlterTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDispTeamMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesignatePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnAlterTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnDeleteTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnDispTeamMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnDesignatePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1220, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// Action performed when the "Back" button is clicked
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);//show the main menu
        dispose(); //hide the current window

    }//GEN-LAST:event_btnBackActionPerformed
    /**
     * Opens a dialog to select a team for alteration and opens the Alter Team
     * Form. Hides the current window after selecting the team.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    private void btnAlterTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterTeamActionPerformed
        // TODO add your handling code here:
        JComboBox comboBox = new JComboBox();
        ArrayList<Team> teamsList = SportsLeagueSystem.getTeamsList();
        if (teamsList.size() == 0) {
            JOptionPane.showMessageDialog(this, "No teams found!");
        } else {
            for (Team team : teamsList) {
                comboBox.addItem("Name: " + team.getTeamName() + " - ID: " + team.getTeamId());
            }
            int choice = JOptionPane.showConfirmDialog(this, comboBox, "Select Team", JOptionPane.OK_CANCEL_OPTION);
            if (choice == JOptionPane.CANCEL_OPTION || choice == JOptionPane.CLOSED_OPTION) {// if clicked cancel or close
                this.setVisible(true); //display current window and hide the pop up
            } else {
                String selectedTeamString = (String) comboBox.getSelectedItem();
                Integer teamId = Integer.parseInt(selectedTeamString.split("ID: ")[1].trim());
                if (teamId != null) {
                    Team tempTeam = SportsLeagueSystem.searchTeam(teamId);
                    AlterTeamForm alterTeam = new AlterTeamForm(this, tempTeam);
                    alterTeam.setVisible(true);
                    dispose();

                }
            }
        }

    }//GEN-LAST:event_btnAlterTeamActionPerformed
    /**
     * Opens the Add Team Form and hides the current window.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    private void btnAddTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeamActionPerformed
        // TODO add your handling code here:
        AddTeamForm addTeamForm = new AddTeamForm();
        addTeamForm.setVisible(true); //show Add Team Form window
        dispose(); //hide the current window
    }//GEN-LAST:event_btnAddTeamActionPerformed
    /**
     * Opens a dialog to select a team and displays the members of that team.
     * Shows an error message if the team has no manager or players.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    private void btnDispTeamMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDispTeamMembersActionPerformed

        JComboBox<String> comboBox = new JComboBox<>();
        ArrayList<Team> teamsList = SportsLeagueSystem.getTeamsList();
        if (teamsList.size() == 0) {
            JOptionPane.showMessageDialog(this, "No teams found!");
        } else {
            for (Team team : teamsList) {
                comboBox.addItem("Name: " + team.getTeamName() + " - ID: " + team.getTeamId());
            }
            int choice = JOptionPane.showConfirmDialog(this, comboBox, "Select Team", JOptionPane.OK_CANCEL_OPTION);
            if (choice == JOptionPane.OK_OPTION) { // If OK button is clicked
                String selectedTeamString = (String) comboBox.getSelectedItem();
                // Extract team ID from the selected item string
                Integer teamId = Integer.parseInt(selectedTeamString.split("ID: ")[1].trim());
                if (teamId != null) {
                    Team tempTeam = SportsLeagueSystem.searchTeam(teamId);
                    //check if the team has members (a manager and players) 
                    if (tempTeam.getTeamPlayers().size() == 0 && tempTeam.getTeamManager() == null) {
                        JOptionPane.showMessageDialog(this, "The team does not have a manager or players!");
                    } else {
                        DisplayTeamMembers dispTeamMembers = new DisplayTeamMembers(tempTeam, this);
                        dispTeamMembers.setVisible(true);
                        this.setVisible(false); // Hide the current window 
                    }

                }
            }

        }

    }//GEN-LAST:event_btnDispTeamMembersActionPerformed
    /**
     * Opens a dialog to select a team and a player to designate as team
     * captain. Shows an error message if no players are found for the team.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    private void btnDesignatePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesignatePlayerActionPerformed

        // TODO add your handling code here:
        JComboBox comboBox = new JComboBox();
        ArrayList<Team> teamsList = SportsLeagueSystem.getTeamsList();
        if (teamsList.size() == 0) {
            JOptionPane.showMessageDialog(this, "No teams found!");
        } else {
            for (Team team : teamsList) {
                comboBox.addItem("Name: " + team.getTeamName() + " - ID: " + team.getTeamId());
            }
            int choice = JOptionPane.showConfirmDialog(this, comboBox, "Select Team", JOptionPane.OK_CANCEL_OPTION);
            if (choice == JOptionPane.OK_OPTION) { // If OK button is clicked
                String selectedTeam = (String) comboBox.getSelectedItem();
                int teamId = Integer.parseInt(selectedTeam.substring(selectedTeam.lastIndexOf("ID: ") + 4));

                // Check if teamId is not null
                if (selectedTeam != null) {
                    JComboBox cb = new JComboBox();
                    ArrayList<Player> playersList = SportsLeagueSystem.searchTeam(teamId).getTeamPlayers();
                    if (playersList.size() == 0) {
                        JOptionPane.showMessageDialog(this, "No players found for this team!");
                    } else {
                        for (Player player : playersList) {
                            cb.addItem("Name: " + player.getMemberName() + " - ID: " + player.getMemberId());
                        }
                        int choice1 = JOptionPane.showConfirmDialog(this, cb, "Select Player", JOptionPane.OK_CANCEL_OPTION);
                        if (choice1 == JOptionPane.OK_OPTION) { // If OK button is clicked
                            String selectedPlayer = (String) cb.getSelectedItem();
                            int playerId = Integer.parseInt(selectedPlayer.substring(selectedPlayer.lastIndexOf("ID: ") + 4));
                            //check if the player is already the team captain 
                            Player tempPlayer = (Player) SportsLeagueSystem.searchMember(playerId);
                            if (tempPlayer.isCaptain() == true) {
                                JOptionPane.showMessageDialog(this, "The player is already the team captain!");
                            } else {
                                //if the player is not the current team captain, call the method to designate the player
                                SportsLeagueSystem.designatePlayerAsCaptain(teamId, playerId);
                                JOptionPane.showMessageDialog(this, "The player has been designated successfully!");
                            }

                        }
                    }
                }

            }
        }
    }//GEN-LAST:event_btnDesignatePlayerActionPerformed
    /**
     * Opens a dialog to select a team for deletion. Deletes the selected team
     * after confirmation and shows a success message.
     *
     * @author Maryam Mohsen, Fatima Khamis, Zahra Husain
     */
    private void btnDeleteTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTeamActionPerformed
        // TODO add your handling code here:
        JComboBox<String> comboBox = new JComboBox<>();
        ArrayList<Team> teamsList = SportsLeagueSystem.getTeamsList();
        if (teamsList.size() == 0) {
            JOptionPane.showMessageDialog(this, "No teams found!");
        } else {
            for (Team team : teamsList) {
                comboBox.addItem("Name: " + team.getTeamName() + " - ID: " + team.getTeamId());
            }
            int choice = JOptionPane.showConfirmDialog(this, comboBox, "Select Team", JOptionPane.OK_CANCEL_OPTION);
            if (choice == JOptionPane.OK_OPTION) {
                String selectedItem = (String) comboBox.getSelectedItem();
                if (selectedItem != null) {
                    // Extract team ID only the number from the selected item
                    String[] parts = selectedItem.split("- ID:"); // Split the string based on "- ID:"

                    if (parts.length == 2) {
                        String teamIdStr = parts[1].trim(); // Get the second part and remove leading/trailing spaces
                        try {
                            int teamId = Integer.parseInt(teamIdStr); // Parse the team ID
                            System.out.println("team ID ---: " + teamId);
                            //confirmation message 
                            int confirmationResult = JOptionPane.showConfirmDialog(this, "Are you certain you want to delete this team?");

                            if (confirmationResult == JOptionPane.YES_OPTION) {
                                // User clicked Yes
                                //delete the team
                                SportsLeagueSystem.deleteTeam(teamId);
                                //display success message
                                JOptionPane.showMessageDialog(this, "The team has been deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                            }

                        } catch (NumberFormatException e) {
                            // Handle the case where parsing fails
                            e.printStackTrace(); // or handle it in another appropriate way
                        }
                    }

                }

            }

        }

    }//GEN-LAST:event_btnDeleteTeamActionPerformed
// Action performed when the "Exit" button is clicked
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0); //exit the system
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnAddTeamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTeamMouseEntered
        // TODO add your handling code here:
        btnAddTeam.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnAddTeamMouseEntered

    private void btnAlterTeamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterTeamMouseEntered
        // TODO add your handling code here:
        btnAlterTeam.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnAlterTeamMouseEntered

    private void btnDeleteTeamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteTeamMouseEntered
        // TODO add your handling code here:
        btnDeleteTeam.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnDeleteTeamMouseEntered

    private void btnDispTeamMembersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDispTeamMembersMouseEntered
        // TODO add your handling code here:
        btnDispTeamMembers.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnDispTeamMembersMouseEntered

    private void btnDesignatePlayerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesignatePlayerMouseEntered
        // TODO add your handling code here:
        btnDesignatePlayer.setBackground(java.awt.Color.decode("#CB997E"));
    }//GEN-LAST:event_btnDesignatePlayerMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnBackMouseExited

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnAddTeamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTeamMouseExited
        // TODO add your handling code here:
        btnAddTeam.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnAddTeamMouseExited

    private void btnAlterTeamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterTeamMouseExited
        // TODO add your handling code here:
        btnAlterTeam.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnAlterTeamMouseExited

    private void btnDeleteTeamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteTeamMouseExited
        // TODO add your handling code here:
        btnDeleteTeam.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnDeleteTeamMouseExited

    private void btnDispTeamMembersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDispTeamMembersMouseExited
        // TODO add your handling code here:
        btnDispTeamMembers.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnDispTeamMembersMouseExited

    private void btnDesignatePlayerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesignatePlayerMouseExited
        // TODO add your handling code here:
        btnDesignatePlayer.setBackground(java.awt.Color.decode("#DDBEA9"));
    }//GEN-LAST:event_btnDesignatePlayerMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamsOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamsOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamsOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamsOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamsOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTeam;
    private javax.swing.JButton btnAlterTeam;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteTeam;
    private javax.swing.JButton btnDesignatePlayer;
    private javax.swing.JButton btnDispTeamMembers;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
